version: "3.8"
services:
  db:
    image: postgres
    container_name: pg_c
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_c
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ashahreaz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_c
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog:/var/lib/mailhog

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack_c
    ports:
      - "6379:6379"
      - "8003:8001"
    environment:
      - REDIS_ARGS=--requirepass mypassword
    volumes:
      - redis-stack:/var/lib/redis-stack/data

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  local_pgdata:
  pgadmin-data:
  mailhog:
  redis-stack:
  rabbitmq_data:
