version: "3.8"
services:
  db:
    image: postgres
    container_name: pg_c
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_c
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ashahreaz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_c
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog:/var/lib/mailhog

volumes:
  local_pgdata:
  pgadmin-data:
  mailhog:
