-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'USER';

-- AlterTable
ALTER TABLE "VerificationCode" ALTER COLUMN "status" SET DEFAULT 'PENDING',
ALTER COLUMN "type" SET DEFAULT 'ACCOUNT_ACTIVATION';
